### ISSUE TITLE
Creating requriements.txt file.

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Stake#2]

**Comment by gr33nm0nk2802** [comment]
I would like to work on this issue

**Comment by gr33nm0nk2802** [comment]
I would like to work on issue#2 creating requirements.txt file

**Comment by 0xPrateek** [comment]
Okay, I assigning you for this issue. Please make sure to update us your progress by commenting.

**Comment by gr33nm0nk2802** [comment]
Hello I just observed there are a few errors in the file so, correcting them, will create an issue after creating the PR as we can be assigned 1 Issue at a time

**Comment by gr33nm0nk2802** [comment]
solved issue #2
