### ISSUE TITLE
custom exit message on ctrl+c keyboard event

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Stake#7]
Currently pressing ctrl+c simply exits the program.
It would be nice if we can handle that and print something nice like Canceled by the user or something similar.

**Comment by yashasvini121** [comment]
Hi @0xPrateek , Can you assign me this issue under JWOC?

**Comment by 0xPrateek** [comment]
This is a very old project and is not actively maintained.
I will suggest you to look for a very good project with good code.
